name: Build and Test

on:
    push:
        branches:
            - master
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v5
              with:
                  global-json-file: global.json
            - name: Build and Test
              run: dotnet fsi build.fsx -- -p build
            - name: Upload Artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: bin-${{matrix.os}}
                  path: bin/*.*

    generate-docs:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v5
              with:
                  global-json-file: global.json
            - name: Restore Tools
              run: dotnet tool restore
            - name: Restore
              run: dotnet restore
            - name: Copy CHANGELOG to docs
              run: cp CHANGELOG.md docs/api/CHANGELOG.md
            - name: DocFX Build
              working-directory: docs
              run: dotnet docfx docfx.json
              continue-on-error: false
            - name: Publish
              if: github.event_name == 'push'
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/_site
                  force_orphan: true
